// Copyright 2023 Fortinet, Inc. All rights reserved.
// Author:
// Hongbin Lu (@fgtdev-hblu), Xing Li (@lix-fortinet), Jie Xue (@JieX19)
// Documentation:
// Hongbin Lu (@fgtdev-hblu), Xing Li (@lix-fortinet), Jie Xue (@JieX19)
// Yue Wang (@yuew-ftnt), Liang Liu (@Liang_FTNT)

// Description: Provider for FortiSwitch

package fortiswitch

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// Provider creates and returns the FortiSwitch *schema.Provider.
func Provider() *schema.Provider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"hostname": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "The hostname/IP address of the FortiSwitch to be connected",
			},

			"username": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "The username of the FortiSwitch",
			},

			"password": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "The password of the FortiSwitch to be connected",
			},

			"insecure": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "",
			},

			"cabundlefile": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "CA Bundle file",
			},

			"cabundlecontent": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "CA Bundle file content",
			},

			"http_proxy": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "HTTP proxy address",
			},

			"peerauth": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "disable",
				Description: "Enable/disable peer authentication, can be 'enable' or 'disable'",
			},

			"cacert": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "CA certtificate(Optional)",
			},

			"clientcert": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "User certificate",
			},

			"clientkey": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "User private key",
			},
		},

		DataSourcesMap: map[string]*schema.Resource{
			"fortiswitch_json_generic_api":                 dataSourceJSONGenericAPI(),
			"fortiswitch_router_accesslist":                dataSourceRouterAccessList(),
			"fortiswitch_router_accesslist6":               dataSourceRouterAccessList6(),
			"fortiswitch_router_aspathlist":                dataSourceRouterAspathList(),
			"fortiswitch_router_authpath":                  dataSourceRouterAuthPath(),
			"fortiswitch_router_bgp":                       dataSourceRouterBgp(),
			"fortiswitch_router_communitylist":             dataSourceRouterCommunityList(),
			"fortiswitch_router_isis":                      dataSourceRouterIsis(),
			"fortiswitch_router_keychain":                  dataSourceRouterKeyChain(),
			"fortiswitch_router_multicast":                 dataSourceRouterMulticast(),
			"fortiswitch_router_multicastflow":             dataSourceRouterMulticastFlow(),
			"fortiswitch_router_ospf":                      dataSourceRouterOspf(),
			"fortiswitch_router_ospf6":                     dataSourceRouterOspf6(),
			"fortiswitch_router_policy":                    dataSourceRouterPolicy(),
			"fortiswitch_router_prefixlist":                dataSourceRouterPrefixList(),
			"fortiswitch_router_prefixlist6":               dataSourceRouterPrefixList6(),
			"fortiswitch_router_rip":                       dataSourceRouterRip(),
			"fortiswitch_router_ripng":                     dataSourceRouterRipng(),
			"fortiswitch_router_routemap":                  dataSourceRouterRouteMap(),
			"fortiswitch_router_setting":                   dataSourceRouterSetting(),
			"fortiswitch_router_static":                    dataSourceRouterStatic(),
			"fortiswitch_router_static6":                   dataSourceRouterStatic6(),
			"fortiswitch_system_accprofile":                dataSourceSystemAccprofile(),
			"fortiswitch_system_admin":                     dataSourceSystemAdmin(),
			"fortiswitch_system_arptable":                  dataSourceSystemArpTable(),
			"fortiswitch_system_autoscript":                dataSourceSystemAutoScript(),
			"fortiswitch_system_automationaction":          dataSourceSystemAutomationAction(),
			"fortiswitch_system_automationdestination":     dataSourceSystemAutomationDestination(),
			"fortiswitch_system_automationtrigger":         dataSourceSystemAutomationTrigger(),
			"fortiswitch_system_centralmanagement":         dataSourceSystemCentralManagement(),
			"fortiswitch_system_console":                   dataSourceSystemConsole(),
			"fortiswitch_system_dns":                       dataSourceSystemDns(),
			"fortiswitch_system_dnsdatabase":               dataSourceSystemDnsDatabase(),
			"fortiswitch_system_dnsserver":                 dataSourceSystemDnsServer(),
			"fortiswitch_system_emailserver":               dataSourceSystemEmailServer(),
			"fortiswitch_system_fm":                        dataSourceSystemFm(),
			"fortiswitch_system_fortiguard":                dataSourceSystemFortiguard(),
			"fortiswitch_system_fortimanager":              dataSourceSystemFortimanager(),
			"fortiswitch_system_global":                    dataSourceSystemGlobal(),
			"fortiswitch_system_interface":                 dataSourceSystemInterface(),
			"fortiswitch_system_ipv6neighborcache":         dataSourceSystemIpv6NeighborCache(),
			"fortiswitch_system_linkmonitor":               dataSourceSystemLinkMonitor(),
			"fortiswitch_system_managementtunnel":          dataSourceSystemManagementTunnel(),
			"fortiswitch_system_ntp":                       dataSourceSystemNtp(),
			"fortiswitch_system_passwordpolicy":            dataSourceSystemPasswordPolicy(),
			"fortiswitch_system_proxyarp":                  dataSourceSystemProxyArp(),
			"fortiswitch_system_resourcelimits":            dataSourceSystemResourceLimits(),
			"fortiswitch_system_sessionttl":                dataSourceSystemSessionTtl(),
			"fortiswitch_system_sflow":                     dataSourceSystemSflow(),
			"fortiswitch_system_tosbasedpriority":          dataSourceSystemTosBasedPriority(),
			"fortiswitch_system_vxlan":                     dataSourceSystemVxlan(),
			"fortiswitch_system_zone":                      dataSourceSystemZone(),
			"fortiswitch_systemautoupdate_pushupdate":      dataSourceSystemAutoupdatePushUpdate(),
			"fortiswitch_systemautoupdate_schedule":        dataSourceSystemAutoupdateSchedule(),
			"fortiswitch_systemautoupdate_tunneling":       dataSourceSystemAutoupdateTunneling(),
			"fortiswitch_systemdhcp_server":                dataSourceSystemDhcpServer(),
			"fortiswitch_systemsnmp_community":             dataSourceSystemSnmpCommunity(),
			"fortiswitch_systemsnmp_sysinfo":               dataSourceSystemSnmpSysinfo(),
			"fortiswitch_systemsnmp_user":                  dataSourceSystemSnmpUser(),
			"fortiswitch_routerbgp_neighbor":               dataSourceRouterbgpNeighbor(),
			"fortiswitch_router_accesslistlist":            dataSourceRouterAccessListList(),
			"fortiswitch_router_accesslist6list":           dataSourceRouterAccessList6List(),
			"fortiswitch_router_aspathlistlist":            dataSourceRouterAspathListList(),
			"fortiswitch_router_authpathlist":              dataSourceRouterAuthPathList(),
			"fortiswitch_router_communitylistlist":         dataSourceRouterCommunityListList(),
			"fortiswitch_router_keychainlist":              dataSourceRouterKeyChainList(),
			"fortiswitch_router_multicastflowlist":         dataSourceRouterMulticastFlowList(),
			"fortiswitch_router_policylist":                dataSourceRouterPolicyList(),
			"fortiswitch_router_prefixlistlist":            dataSourceRouterPrefixListList(),
			"fortiswitch_router_prefixlist6list":           dataSourceRouterPrefixList6List(),
			"fortiswitch_router_routemaplist":              dataSourceRouterRouteMapList(),
			"fortiswitch_router_staticlist":                dataSourceRouterStaticList(),
			"fortiswitch_router_static6list":               dataSourceRouterStatic6List(),
			"fortiswitch_system_accprofilelist":            dataSourceSystemAccprofileList(),
			"fortiswitch_system_adminlist":                 dataSourceSystemAdminList(),
			"fortiswitch_system_arptablelist":              dataSourceSystemArpTableList(),
			"fortiswitch_system_autoscriptlist":            dataSourceSystemAutoScriptList(),
			"fortiswitch_system_automationactionlist":      dataSourceSystemAutomationActionList(),
			"fortiswitch_system_automationdestinationlist": dataSourceSystemAutomationDestinationList(),
			"fortiswitch_system_automationtriggerlist":     dataSourceSystemAutomationTriggerList(),
			"fortiswitch_system_dnsdatabaselist":           dataSourceSystemDnsDatabaseList(),
			"fortiswitch_system_dnsserverlist":             dataSourceSystemDnsServerList(),
			"fortiswitch_system_interfacelist":             dataSourceSystemInterfaceList(),
			"fortiswitch_system_ipv6neighborcachelist":     dataSourceSystemIpv6NeighborCacheList(),
			"fortiswitch_system_linkmonitorlist":           dataSourceSystemLinkMonitorList(),
			"fortiswitch_system_proxyarplist":              dataSourceSystemProxyArpList(),
			"fortiswitch_system_tosbasedprioritylist":      dataSourceSystemTosBasedPriorityList(),
			"fortiswitch_system_vxlanlist":                 dataSourceSystemVxlanList(),
			"fortiswitch_system_zonelist":                  dataSourceSystemZoneList(),
			"fortiswitch_systemdhcp_serverlist":            dataSourceSystemDhcpServerList(),
			"fortiswitch_systemsnmp_communitylist":         dataSourceSystemSnmpCommunityList(),
			"fortiswitch_systemsnmp_userlist":              dataSourceSystemSnmpUserList(),
			"fortiswitch_routerbgp_neighborlist":           dataSourceRouterbgpNeighborList(),
		},

		ResourcesMap: map[string]*schema.Resource{
			"fortiswitch_alertemail_setting":               resourceAlertemailSetting(),
			"fortiswitch_json_generic_api":                 resourceJSONGenericAPI(),
			"fortiswitch_gui_console":                      resourceGuiConsole(),
			"fortiswitch_log_customfield":                  resourceLogCustomField(),
			"fortiswitch_log_eventfilter":                  resourceLogEventfilter(),
			"fortiswitch_log_gui":                          resourceLogGui(),
			"fortiswitch_logdisk_filter":                   resourceLogDiskFilter(),
			"fortiswitch_logdisk_setting":                  resourceLogDiskSetting(),
			"fortiswitch_logfortianalyzer_filter":          resourceLogFortianalyzerFilter(),
			"fortiswitch_logfortianalyzer_overridefilter":  resourceLogFortianalyzerOverrideFilter(),
			"fortiswitch_logfortianalyzer_overridesetting": resourceLogFortianalyzerOverrideSetting(),
			"fortiswitch_logfortianalyzer_setting":         resourceLogFortianalyzerSetting(),
			"fortiswitch_logfortianalyzer2_filter":         resourceLogFortianalyzer2Filter(),
			"fortiswitch_logfortianalyzer2_setting":        resourceLogFortianalyzer2Setting(),
			"fortiswitch_logfortianalyzer3_filter":         resourceLogFortianalyzer3Filter(),
			"fortiswitch_logfortianalyzer3_setting":        resourceLogFortianalyzer3Setting(),
			"fortiswitch_logfortiguard_setting":            resourceLogFortiguardSetting(),
			"fortiswitch_logmemory_filter":                 resourceLogMemoryFilter(),
			"fortiswitch_logmemory_globalsetting":          resourceLogMemoryGlobalSetting(),
			"fortiswitch_logmemory_setting":                resourceLogMemorySetting(),
			"fortiswitch_logremote_setting":                resourceLogRemoteSetting(),
			"fortiswitch_logsyslogd_filter":                resourceLogSyslogdFilter(),
			"fortiswitch_logsyslogd_overridefilter":        resourceLogSyslogdOverrideFilter(),
			"fortiswitch_logsyslogd_overridesetting":       resourceLogSyslogdOverrideSetting(),
			"fortiswitch_logsyslogd_setting":               resourceLogSyslogdSetting(),
			"fortiswitch_logsyslogd2_filter":               resourceLogSyslogd2Filter(),
			"fortiswitch_logsyslogd2_setting":              resourceLogSyslogd2Setting(),
			"fortiswitch_logsyslogd3_filter":               resourceLogSyslogd3Filter(),
			"fortiswitch_logsyslogd3_setting":              resourceLogSyslogd3Setting(),
			"fortiswitch_router_accesslist":                resourceRouterAccessList(),
			"fortiswitch_router_accesslist6":               resourceRouterAccessList6(),
			"fortiswitch_router_aspathlist":                resourceRouterAspathList(),
			"fortiswitch_router_authpath":                  resourceRouterAuthPath(),
			"fortiswitch_router_bgp":                       resourceRouterBgp(),
			"fortiswitch_router_communitylist":             resourceRouterCommunityList(),
			"fortiswitch_router_gwdetect":                  resourceRouterGwdetect(),
			"fortiswitch_router_isis":                      resourceRouterIsis(),
			"fortiswitch_router_keychain":                  resourceRouterKeyChain(),
			"fortiswitch_router_multicast":                 resourceRouterMulticast(),
			"fortiswitch_router_multicastflow":             resourceRouterMulticastFlow(),
			"fortiswitch_router_ospf":                      resourceRouterOspf(),
			"fortiswitch_router_ospf6":                     resourceRouterOspf6(),
			"fortiswitch_router_policy":                    resourceRouterPolicy(),
			"fortiswitch_router_prefixlist":                resourceRouterPrefixList(),
			"fortiswitch_router_prefixlist6":               resourceRouterPrefixList6(),
			"fortiswitch_router_rip":                       resourceRouterRip(),
			"fortiswitch_router_ripng":                     resourceRouterRipng(),
			"fortiswitch_router_routemap":                  resourceRouterRouteMap(),
			"fortiswitch_router_setting":                   resourceRouterSetting(),
			"fortiswitch_router_static":                    resourceRouterStatic(),
			"fortiswitch_router_static6":                   resourceRouterStatic6(),
			"fortiswitch_router_vrf":                       resourceRouterVrf(),
			"fortiswitch_switch_autoislportgroup":          resourceSwitchAutoIslPortGroup(),
			"fortiswitch_switch_autonetwork":               resourceSwitchAutoNetwork(),
			"fortiswitch_switch_domain":                    resourceSwitchDomain(),
			"fortiswitch_switch_global":                    resourceSwitchGlobal(),
			"fortiswitch_switch_interface":                 resourceSwitchInterface(),
			"fortiswitch_switch_ipmacbinding":              resourceSwitchIpMacBinding(),
			"fortiswitch_switch_mirror":                    resourceSwitchMirror(),
			"fortiswitch_switch_phymode":                   resourceSwitchPhyMode(),
			"fortiswitch_switch_physicalport":              resourceSwitchPhysicalPort(),
			"fortiswitch_switch_quarantine":                resourceSwitchQuarantine(),
			"fortiswitch_switch_raguardpolicy":             resourceSwitchRaguardPolicy(),
			"fortiswitch_switch_securityfeature":           resourceSwitchSecurityFeature(),
			"fortiswitch_switch_staticmac":                 resourceSwitchStaticMac(),
			"fortiswitch_switch_stormcontrol":              resourceSwitchStormControl(),
			"fortiswitch_switch_trunk":                     resourceSwitchTrunk(),
			"fortiswitch_switch_virtualwire":               resourceSwitchVirtualWire(),
			"fortiswitch_switch_vlan":                      resourceSwitchVlan(),
			"fortiswitch_switch_vlantpid":                  resourceSwitchVlanTpid(),
			"fortiswitch_switchcontroller_global":          resourceSwitchControllerGlobal(),
			"fortiswitch_switchacl_8021X":                  resourceSwitchAcl8021X(),
			"fortiswitch_switchacl_egress":                 resourceSwitchAclEgress(),
			"fortiswitch_switchacl_ingress":                resourceSwitchAclIngress(),
			"fortiswitch_switchacl_policer":                resourceSwitchAclPolicer(),
			"fortiswitch_switchacl_prelookup":              resourceSwitchAclPrelookup(),
			"fortiswitch_switchacl_settings":               resourceSwitchAclSettings(),
			"fortiswitch_switchaclservice_custom":          resourceSwitchAclServiceCustom(),
			"fortiswitch_switchigmpsnooping_globals":       resourceSwitchIgmpSnoopingGlobals(),
			"fortiswitch_switchlldp_profile":               resourceSwitchLldpProfile(),
			"fortiswitch_switchlldp_settings":              resourceSwitchLldpSettings(),
			"fortiswitch_switchmacsec_profile":             resourceSwitchMacsecProfile(),
			"fortiswitch_switchmldsnooping_globals":        resourceSwitchMldSnoopingGlobals(),
			"fortiswitch_switchnetworkmonitor_directed":    resourceSwitchNetworkMonitorDirected(),
			"fortiswitch_switchnetworkmonitor_settings":    resourceSwitchNetworkMonitorSettings(),
			"fortiswitch_switchptp_policy":                 resourceSwitchPtpPolicy(),
			"fortiswitch_switchptp_settings":               resourceSwitchPtpSettings(),
			"fortiswitch_switchqos_dot1pmap":               resourceSwitchQosDot1PMap(),
			"fortiswitch_switchqos_ipdscpmap":              resourceSwitchQosIpDscpMap(),
			"fortiswitch_switchqos_qospolicy":              resourceSwitchQosQosPolicy(),
			"fortiswitch_switchstp_instance":               resourceSwitchStpInstance(),
			"fortiswitch_switchstp_settings":               resourceSwitchStpSettings(),
			"fortiswitch_system_accprofile":                resourceSystemAccprofile(),
			"fortiswitch_system_admin":                     resourceSystemAdmin(),
			"fortiswitch_system_alarm":                     resourceSystemAlarm(),
			"fortiswitch_system_alertemail":                resourceSystemAlertemail(),
			"fortiswitch_system_arptable":                  resourceSystemArpTable(),
			"fortiswitch_system_autoscript":                resourceSystemAutoScript(),
			"fortiswitch_system_automationaction":          resourceSystemAutomationAction(),
			"fortiswitch_system_automationdestination":     resourceSystemAutomationDestination(),
			"fortiswitch_system_automationstitch":          resourceSystemAutomationStitch(),
			"fortiswitch_system_automationtrigger":         resourceSystemAutomationTrigger(),
			"fortiswitch_system_bugreport":                 resourceSystemBugReport(),
			"fortiswitch_system_centralmanagement":         resourceSystemCentralManagement(),
			"fortiswitch_system_console":                   resourceSystemConsole(),
			"fortiswitch_system_dns":                       resourceSystemDns(),
			"fortiswitch_system_dnsdatabase":               resourceSystemDnsDatabase(),
			"fortiswitch_system_dnsserver":                 resourceSystemDnsServer(),
			"fortiswitch_system_emailserver":               resourceSystemEmailServer(),
			"fortiswitch_system_flancloud":                 resourceSystemFlanCloud(),
			"fortiswitch_system_flowexport":                resourceSystemFlowExport(),
			"fortiswitch_system_fm":                        resourceSystemFm(),
			"fortiswitch_system_fortianalyzer":             resourceSystemFortianalyzer(),
			"fortiswitch_system_fortianalyzer2":            resourceSystemFortianalyzer2(),
			"fortiswitch_system_fortianalyzer3":            resourceSystemFortianalyzer3(),
			"fortiswitch_system_fortiguard":                resourceSystemFortiguard(),
			"fortiswitch_system_fortimanager":              resourceSystemFortimanager(),
			"fortiswitch_system_fswcloud":                  resourceSystemFswCloud(),
			"fortiswitch_system_global":                    resourceSystemGlobal(),
			"fortiswitch_system_interface":                 resourceSystemInterface(),
			"fortiswitch_system_ipv6neighborcache":         resourceSystemIpv6NeighborCache(),
			"fortiswitch_system_linkmonitor":               resourceSystemLinkMonitor(),
			"fortiswitch_system_location":                  resourceSystemLocation(),
			"fortiswitch_system_macaddresstable":           resourceSystemMacAddressTable(),
			"fortiswitch_system_managementtunnel":          resourceSystemManagementTunnel(),
			"fortiswitch_system_ntp":                       resourceSystemNtp(),
			"fortiswitch_system_objecttag":                 resourceSystemObjectTag(),
			"fortiswitch_system_passwordpolicy":            resourceSystemPasswordPolicy(),
			"fortiswitch_system_portpair":                  resourceSystemPortPair(),
			"fortiswitch_system_proxyarp":                  resourceSystemProxyArp(),
			"fortiswitch_system_resourcelimits":            resourceSystemResourceLimits(),
			"fortiswitch_system_sessionttl":                resourceSystemSessionTtl(),
			"fortiswitch_system_settings":                  resourceSystemSettings(),
			"fortiswitch_system_sflow":                     resourceSystemSflow(),
			"fortiswitch_system_snifferprofile":            resourceSystemSnifferProfile(),
			"fortiswitch_system_tosbasedpriority":          resourceSystemTosBasedPriority(),
			"fortiswitch_system_vdom":                      resourceSystemVdom(),
			"fortiswitch_system_vdomdns":                   resourceSystemVdomDns(),
			"fortiswitch_system_vdomproperty":              resourceSystemVdomProperty(),
			"fortiswitch_system_vxlan":                     resourceSystemVxlan(),
			"fortiswitch_system_web":                       resourceSystemWeb(),
			"fortiswitch_system_zone":                      resourceSystemZone(),
			"fortiswitch_systemalias_command":              resourceSystemAliasCommand(),
			"fortiswitch_systemalias_group":                resourceSystemAliasGroup(),
			"fortiswitch_systemautoupdate_clientoverride":  resourceSystemAutoupdateClientoverride(),
			"fortiswitch_systemautoupdate_override":        resourceSystemAutoupdateOverride(),
			"fortiswitch_systemautoupdate_pushupdate":      resourceSystemAutoupdatePushUpdate(),
			"fortiswitch_systemautoupdate_schedule":        resourceSystemAutoupdateSchedule(),
			"fortiswitch_systemautoupdate_tunneling":       resourceSystemAutoupdateTunneling(),
			"fortiswitch_systemcertificate_ca":             resourceSystemCertificateCa(),
			"fortiswitch_systemcertificate_crl":            resourceSystemCertificateCrl(),
			"fortiswitch_systemcertificate_local":          resourceSystemCertificateLocal(),
			"fortiswitch_systemcertificate_ocsp":           resourceSystemCertificateOcsp(),
			"fortiswitch_systemcertificate_remote":         resourceSystemCertificateRemote(),
			"fortiswitch_systemdhcp_server":                resourceSystemDhcpServer(),
			"fortiswitch_systemschedule_group":             resourceSystemScheduleGroup(),
			"fortiswitch_systemschedule_onetime":           resourceSystemScheduleOnetime(),
			"fortiswitch_systemschedule_recurring":         resourceSystemScheduleRecurring(),
			"fortiswitch_systemsnmp_community":             resourceSystemSnmpCommunity(),
			"fortiswitch_systemsnmp_sysinfo":               resourceSystemSnmpSysinfo(),
			"fortiswitch_systemsnmp_user":                  resourceSystemSnmpUser(),
			"fortiswitch_user_group":                       resourceUserGroup(),
			"fortiswitch_user_ldap":                        resourceUserLdap(),
			"fortiswitch_user_local":                       resourceUserLocal(),
			"fortiswitch_user_peer":                        resourceUserPeer(),
			"fortiswitch_user_peergrp":                     resourceUserPeergrp(),
			"fortiswitch_user_radius":                      resourceUserRadius(),
			"fortiswitch_user_setting":                     resourceUserSetting(),
			"fortiswitch_user_tacacs":                      resourceUserTacacs(),
			"fortiswitch_routerbgp_neighbor":               resourceRouterbgpNeighbor(),
			"fortiswitch_routerbgp_network":                resourceRouterbgpNetwork(),
			"fortiswitch_routerbgp_network6":               resourceRouterbgpNetwork6(),
			"fortiswitch_routerospf_network":               resourceRouterospfNetwork(),
		},

		ConfigureFunc: providerConfigure,
	}
}

func providerConfigure(d *schema.ResourceData) (interface{}, error) {

	// Init client config with the values from TF files
	config := Config{
		Hostname:        d.Get("hostname").(string),
		Username:        d.Get("username").(string),
		Password:        d.Get("password").(string),
		CABundle:        d.Get("cabundlefile").(string),
		CABundleContent: d.Get("cabundlecontent").(string),

		PeerAuth:   d.Get("peerauth").(string),
		CaCert:     d.Get("cacert").(string),
		ClientCert: d.Get("clientcert").(string),
		ClientKey:  d.Get("clientkey").(string),
	}

	v1, ok1 := d.GetOkExists("insecure")
	if ok1 {
		insecure := v1.(bool)
		config.Insecure = &insecure
	}

	// Create Client for later connections
	return config.CreateClient()
}
